import { resolve } from "node:path";
import { writeCode } from "./utils";

export async function generateCSS(cssVars: Record<string, string>) {
  const props = Object.entries(cssVars).map((theme) => {
    const [prop, value] = theme;
    return `  ${prop}: ${value};`;
  });

  const codes = `/* This file is generated by scripts/generate-css.ts */

:root {
${props.join("\n")}
}`;

  await writeCode(resolve(process.cwd(), "./src/css/theme.module.css"), codes);
}
